flairstyle_shop/apps/accounts/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("", views.dashboard, name="dashboard"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("forgotPassword/", views.forgotPassword, name="forgotPassword"),
    path(
        "resetPassword_validate/<uidb64>/<token>/",
        views.resetPassword_validate,
        name="resetPassword_validate",
    ),
    path("resetPassword/", views.resetPassword, name="resetPassword"),
    path("my_orders/", views.my_orders, name="my_orders"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("change_password/", views.change_password, name="change_password"),
    path("order_detail/<int:order_id>/", views.order_detail, name="order_detail"),
]

flairstyle_shop/core/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    # path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("securelogin/", admin.site.urls),
    path("", views.home, name="home"),
    path("store/", include("apps.store.urls")),
    path("cart/", include("apps.carts.urls")),
    path("accounts/", include("apps.accounts.urls")),
    path("orders/", include("apps.orders.urls")),
    path("weather_clothes/", include("apps.weather_clothes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

flairstyle_shop/apps/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager
from django.db import models
from typing import Literal


class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("User must have an email address")

        if not username:
            raise ValueError("User must have an username")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_active = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name", "last_name"]

    objects = MyAccountManager()

    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def __str__(self) -> str:
        return self.email

    def has_perm(self, perm, obj=None) -> bool:
        return self.is_admin

    def has_module_perms(self, add_label) -> Literal[True]:
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True, max_length=100)
    address_line_2 = models.CharField(blank=True, max_length=100)
    profile_picture = models.ImageField(blank=True, upload_to="userprofile/")
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def full_address(self) -> str:
        return f"{self.address_line_1} {self.address_line_2}"

    def __str__(self) -> str:
        return self.user.first_name

flairstyle_shop/apps/accounts/forms.py
from .models import Account
from .models import UserProfile
from django import forms


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Enter Password",
            }
        )
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm Password",
            }
        )
    )

    class Meta:
        model = Account
        fields = ("first_name", "last_name", "phone_number", "email", "password")

        def clean(self) -> None:
            # TODO: Fix this
            # ERROR: Cannot access member "clean" for type "object"
            cleaned_data = super().clean()  # type: ignore
            password = cleaned_data.get("password")
            confirm_password = cleaned_data.get("confirm_password")

            if password != confirm_password:
                raise forms.ValidationError("Password does not match!")

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs["placeholder"] = "Enter First Name"
        self.fields["last_name"].widget.attrs["placeholder"] = "Enter Last Name"
        self.fields["phone_number"].widget.attrs["placeholder"] = "Enter Phone Number"
        self.fields["email"].widget.attrs["placeholder"] = "Enter Email Address"
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ("first_name", "last_name", "phone_number")

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(
        required=False,
        error_messages={"invalid": "Image files only"},
        widget=forms.FileInput,
    )

    class Meta:
        model = UserProfile
        fields = (
            "address_line_1",
            "address_line_2",
            "city",
            "state",
            "country",
            "profile_picture",
        )

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

flairstyle_shop/apps/accounts/views.py
from .forms import RegistrationForm
from .forms import UserForm
from .forms import UserProfileForm
from .models import Account
from .models import UserProfile
from apps.carts.models import Cart
from apps.carts.models import CartItem
from apps.carts.views import _cart_id
from apps.orders.models import Order
from apps.orders.models import OrderProduct
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator

# Verification email
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.http import HttpResponsePermanentRedirect
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode
from django.utils.http import urlsafe_base64_encode

import requests


def register(request) -> HttpResponseRedirect | HttpResponsePermanentRedirect | HttpResponse:
    if request.user.is_authenticated:
        return redirect("home")
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            phone_number = form.cleaned_data["phone_number"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            username = email.split("@")[0]
            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                username=username,
                password=password,
            )
            user.phone_number = phone_number
            user.save()

            # Create User Profile
            profile = UserProfile()
            # TODO: Fix this
            # ERROR: Cannot assign member "user_id" for type "UserProfile"
            # ERROR: Cannot assign member "profile_picture" for type "UserProfile"
            profile.user_id = user.id  # type: ignore
            profile.profile_picture = "default/default-user.png"  # type: ignore
            profile.save()

            # User Activation
            current_site = get_current_site(request)
            mail_subject = "Please activate your account"
            message = render_to_string(
                "accounts/account_verification_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, from_email="noreply@gmail.com", to=[to_email])
            send_email.send()
            # messages.success(request, "Check your email to complete registration!")
            return redirect(f"/accounts/login/?command=verification&email={email}")
    else:
        form = RegistrationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/register.html", context)


# TODO: Fix this
# ERROR: 'login' is too complex (15)Flake8(C901)
def login(request) -> HttpResponseRedirect | HttpResponsePermanentRedirect | HttpResponse:  # noqa
    if request.user.is_authenticated:
        return redirect("home")
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]
        user = auth.authenticate(email=email, password=password)
        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_items = CartItem.objects.filter(cart=cart)
                    product_variation = []
                    for item in cart_items:
                        variation = item.variations.all()
                        product_variation.append(list(variation))
                        # item.user = user
                        # item.save()
                    cart_item = CartItem.objects.filter(
                        user=user,
                    )
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        # TODO: Fix this
                        # ERROR: Cannot access member "id" for type "CartItem"
                        id.append(item.id)  # type: ignore

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            # TODO: Fix this
                            # ERROR: Cannot assign member "user" for type "CartItem"
                            item.user = user  # type: ignore
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                # TODO: Fix this
                                # ERROR: Cannot assign member "user" for type "CartItem"
                                item.user = user  # type: ignore
                                item.save()
            # TODO: Fix this
            # ERROR: do not use bare 'except'Flake8(E722)
            except:  # noqa
                pass
            auth.login(request, user)
            messages.success(request, "You are now logged in!")
            url = request.META.get("HTTP_REFERRER")
            try:
                # TODO: Fix this
                # ERROR: "utils" is not a known member of module "requests"
                query = requests.utils.urlparse(url).query  # type: ignore
                params = dict(x.split("=") for x in query.split("&"))
                if "next" in params:
                    nextPage = params["next"]
                    return redirect(nextPage)
            # TODO: Fix this
            # ERROR: do not use bare 'except'Flake8(E722)
            except:  # noqa
                return redirect("dashboard")
        else:
            messages.error(request, "Invalid login credentials")
            return redirect("login")
    return render(request, "accounts/login.html")


@login_required(login_url="login")
def logout(request) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
    auth.logout(request)
    messages.success(request, "You are logged out!")
    return redirect("login")


def activate(request, uidb64, token) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations! Your account is activated.")
        return redirect("login")
    else:
        messages.error(request, "Invalid activation link")
        return redirect("register")


@login_required(login_url="login")
def dashboard(request) -> HttpResponse:
    orders = Order.objects.order_by("-created_at").filter(user_id=request.user.id, is_ordered=True)
    orders_count = orders.count()
    userprofile = UserProfile.objects.get(user__id=request.user.id)
    ctx = {
        "orders_count": orders_count,
        "userprofile": userprofile,
    }
    return render(request, "accounts/dashboard.html", ctx)


def forgotPassword(request) -> HttpResponseRedirect | HttpResponsePermanentRedirect | HttpResponse:
    if request.method == "POST":
        email = request.POST["email"]
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__iexact=email)
            current_site = get_current_site(request)
            mail_subject = "Reset your password"
            message = render_to_string(
                "accounts/reset_password_email.html",
                {
                    "user": user,
                    "domain": current_site,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": default_token_generator.make_token(user),
                },
            )
            to_email = email
            send_email = EmailMessage(mail_subject, message, from_email="noreply@gmail.com", to=[to_email])
            send_email.send()

            messages.success(request, "Password reset email has been sent to your email address")
            return redirect("login")

        else:
            messages.error(request, "Account does not exist!")
            return redirect("forgotPassword")
    return render(request, "accounts/forgotPassword.html")


def resetPassword_validate(request, uidb64, token) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        # TODO: Fix this
        # ERROR: "uid" is possibly unbound

flairstyle_shop/templates/accounts/account_verification_email.html
{% autoescape off %}

Привет, {{ user.first_name }},

Перейдите по ссылке ниже, чтобы подтвердить регистрацию!
http://{{domain}}{% url 'activate' uidb64=uid token=token %}

Если ты думаешь, что письмо отправлено не тебе, пожалуйста проигнорируй его.

{% endautoescape %}

flairstyle_shop/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
<section class="section-conten padding-y bg">
  {% include 'includes/alerts.html' %}
  <div class="container">
    <div class="row">
      {% include 'includes/dashboard_sidebar.html' %}
      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Смена пароля</strong>
          </header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-12">
                <form action="{% url 'change_password' %}" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label>Текущий пароль</label>
                    <input type="password" name="current_password" placeholder="Current password" class="form-control"
                      required>
                  </div>
                  <div class="form-group">
                    <label>Новый пароль</label>
                    <input type="password" name="new_password" placeholder="Create new password" class="form-control"
                      required>
                  </div>
                  <div class="form-group">
                    <label>Подтверди новый пароль</label>
                    <input type="password" name="confirm_new_password" placeholder="Confirm new password"
                      class="form-control" required>
                  </div>
                  <input type="submit" value="Submit" class="btn btn-primary">
                </form>
              </div>
            </div> <!-- row.// -->
          </div> <!-- card-body .// -->
        </article> <!-- order-group.// -->
      </main>
    </div> <!-- row.// -->
  </div>
</section>
{% endblock content %}

flairstyle_shop/templates/accounts/dashboard.html
{% extends "base.html" %}
{% block content %}
<section class="section-conten padding-y bg">
  {% include 'includes/alerts.html' %}
  <div class="container">
    <div class="row">
      {% include 'includes/dashboard_sidebar.html' %}
      <main class="col-md-9">
        <article class="card" style="text-align:center;">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Вошел как: </strong>
            <span>{{ user.full_name }}</span>
          </header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <div class="card" style="text-align:center;">
                  <div class="card-body">
                    <h5 class="card-title">Все заказы</h5>
                    <h4>{{orders_count}}</h4>
                    <a href="{% url 'my_orders' %}">Просмотреть заказы</a>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="card" style="text-align:center;">
                  <div class="card-body">
                    <img src="{{ userprofile.profile_picture.url }}" alt="User Profile Picture" width="50"
                      height="50" style="border-radius:50%;">
                    <p class="mb-0">{{ user.email }}</p>
                    <p>{{ user.phone_number }}</p>
                  </div>
                </div>
              </div>
            </div> <!-- row.// -->
          </div> <!-- card-body .// -->
        </article> <!-- order-group.// -->
      </main>
    </div> <!-- row.// -->
  </div>
</section>
{% endblock content %}

flairstyle_shop/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% block content %}
<section class="section-conten padding-y bg">
  {% include 'includes/alerts.html' %}
  <div class="container">
    <div class="row">
      {% include 'includes/dashboard_sidebar.html' %}
      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Редактировать профиль</strong>
          </header>
          <div class="card-body">
            <div class="text-right">
              <img src="{{ userprofile.profile_picture.url }}" alt="Profile Pocture" width="100" style="border-radius:50px;">
            </div>
            <div class="row">
              <div class="col-md-12">
                <form action="{% url 'edit_profile' %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Имя</label>
                      {{ user_form.first_name }}
                    </div>
                    <div class="form-group col-md-6">
                      <label>Фамилия</label>
                      {{ user_form.last_name }}
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Телефон</label>
                      {{ user_form.phone_number }}
                    </div>
                    <div class="form-group col-md-6">
                      <label>Фото профиля</label>
                      {{ profile_form.profile_picture }}
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Адрес (Улица)</label>
                    {{ profile_form.address_line_1 }}
                  </div>
                  <div class="form-group">
                    <label>Адрес (Номер дома, квартиры)</label>
                    {{ profile_form.address_line_2 }}
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-4">
                      <label>Город</label>
                      {{ profile_form.city }}
                    </div>
                    <div class="form-group col-md-4">
                      <label>Республика</label>
                      {{ profile_form.state }}
                    </div>
                    <div class="form-group col-md-4">
                      <label>Страна</label>
                      {{ profile_form.country }}
                    </div>
                  </div>
                  <input type="submit" value="Save" class="btn btn-primary">
                </form>
              </div>
            </div> <!-- row.// -->
          </div> <!-- card-body .// -->
        </article> <!-- order-group.// -->
      </main>
    </div> <!-- row.// -->
  </div>
</section>
{% endblock content %}

flairstyle_shop/templates/accounts/forgotPassword.html
{% extends "base.html" %}
{% block content %}
<section class="section-conten padding-y" style="min-height:84vh">

  <!-- ============================ COMPONENT LOGIN   ================================= -->
  <div class="card mx-auto" style="max-width: 600px; margin-top:100px;">

    <div class="card-body">
      <h4 class="card-title mb-4">Забыл пароль</h4>
      {% include "includes/alerts.html" %}
      <form action="{% url 'forgotPassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input type="email" class="form-control" placeholder="Email" name='email'>
        </div> <!-- form-group// -->
        <div class="form-group">
          <a href="{% url 'login' %}" class="float-right">Вспомнил пароль? Авторизуйся!</a>
        </div> <!-- form-group form-check .// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block"> Подтвердить </button>
        </div> <!-- form-group// -->
      </form>
    </div> <!-- card-body.// -->
  </div> <!-- card .// -->
  <p class="text-center mt-4">Нет аккаунта? <a href="{% url 'register' %}">Регистрация</a></p>
  <br><br>
  <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
</section>
{% endblock content %}

flairstyle_shop/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<section class="section-conten padding-y" style="min-height:84vh">

  <!-- ============================ COMPONENT LOGIN   ================================= -->
  {% if request.GET.command == 'verification' %}

  <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
    Вам было отправлено письмо для верификации на вашу электронную почту {{ request.GET.email }}
    <br><br>
    Уже подтвредили? <a href="{% url 'login' %}">Авторизоваться</a>
  </div>

  {% else %}
  <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">

    <div class="card-body">
      <h4 class="card-title mb-4">Войти</h4>
      {% include "includes/alerts.html" %}
      <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input type="email" class="form-control" placeholder="Email" name='email'>
        </div> <!-- form-group// -->
        <div class="form-group">
          <input type="password" class="form-control" placeholder="Пароль" name='password'>
        </div> <!-- form-group// -->
        <div class="form-group">
          <a href="{% url 'forgotPassword' %}" class="float-right">Забыл пароль?</a>
        </div> <!-- form-group form-check .// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block"> Войти </button>
        </div> <!-- form-group// -->
      </form>
    </div> <!-- card-body.// -->
  </div> <!-- card .// -->
  <p class="text-center mt-4">Нет аккаунта? <a href="{% url 'register' %}">Зарегистрируйся</a></p>
  <br><br>
  <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
  {% endif %}
</section>
{% endblock content %}

flairstyle_shop/templates/accounts/register.html
{% extends "base.html" %}
{% block content %}
<section class="section-content padding-y">
  <!-- ============================ COMPONENT REGISTER   ================================= -->
  <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
    <article class="card-body">
      {% include 'includes/alerts.html' %}
      <header class="mb-4">
        <h4 class="card-title">Регистрация</h4>
      </header>
      <form action="{% url 'register' %}" method='post'>
        {% csrf_token %}
        <div class="form-row">
          <div class="col form-group">
            <label>Имя</label>
            <input type="text" name="first_name" maxlength="50" placeholder="" class="form-control" required="" id="id_first_name">
          </div> <!-- form-group end.// -->
          <div class="col form-group">
            <label>Фамилия</label>
<!--            {{ form.last_name }}-->
            <input type="text" name="last_name" maxlength="50" placeholder="" class="form-control" required="" id="id_last_name">
          </div> <!-- form-group end.// -->
        </div> <!-- form-row.// -->
        <div class='form-row'>
          <div class="form-group col-md-6">
            <label>Email</label>
<!--            {{ form.email }}-->
            <input type="email" name="email" maxlength="100" placeholder="" class="form-control" required="" id="id_email">
          </div> <!-- form-group end.// -->
          <div class="form-group col-md-6">
            <label>Телефон</label>
            <input type="text" name="phone_number" maxlength="50" placeholder="" class="form-control" required="" id="id_phone_number">
          </div> <!-- form-group end.// -->
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Пароль</label>
            <input type="password" name="password" placeholder="" class="form-control" required="" id="id_password" aria-autocomplete="list">
          </div> <!-- form-group end.// -->
          <div class="form-group col-md-6">
            <label>Повтор пароля</label>
            <input type="password" name="confirm_password" placeholder="" class="form-control" required="" id="id_confirm_password">
          </div> <!-- form-group end.// -->
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block"> Зарегистрироваться </button>
        </div> <!-- form-group// -->
        {{ form.email.errors }}
        {{ form.non_field_errors }}
      </form>
    </article><!-- card-body.// -->
  </div> <!-- card .// -->
  <p class="text-center mt-4">Уже есть аккаунт? <a href="{% url 'login' %}">Авторизоваться</a></p>
  <br><br>
  <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
</section>
{% endblock content %}

flairstyle_shop/templates/accounts/resetPassword.html
{% extends "base.html" %}
{% block content %}
<section class="section-conten padding-y" style="min-height:84vh">

  <!-- ============================ COMPONENT LOGIN   ================================= -->
  <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">

    <div class="card-body">
      <h4 class="card-title mb-4">Сбросить пароль</h4>
      {% include "includes/alerts.html" %}
      <form action="{% url 'resetPassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input type="password" class="form-control" placeholder="Пароль" name='password'>
        </div> <!-- form-group// -->
        <div class="form-group">
          <input type="password" class="form-control" placeholder="Подтверди пароль" name='confirm_password'>
        </div> <!-- form-group// -->

        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block"> Сбросить </button>
        </div> <!-- form-group// -->
      </form>
    </div> <!-- card-body.// -->
  </div> <!-- card .// -->
  <p class="text-center mt-4">Нет аккаунта? <a href="{% url 'register' %}">Зарегистрируйся</a></p>
  <br><br>
  <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
</section>
{% endblock content %}