flairstyle_shop/apps/carts/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path(
        "remove_cart/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart,
        name="remove_cart",
    ),
    path(
        "remove_cart_item/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_item,
        name="remove_cart_item",
    ),
    path("checkout/", views.checkout, name="checkout"),
]

flairstyle_shop/apps/store/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path("", views.store, name="store"),
    path("category/<slug:category_slug>/", views.store, name="products_by_category"),
    path(
        "category/<slug:category_slug>/<slug:product_slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path("search/", views.search, name="search"),
    path("submit_review/<int:product_id>/", views.submit_review, name="submit_review"),
]

flairstyle_shop/core/urls.py
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    # path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("securelogin/", admin.site.urls),
    path("", views.home, name="home"),
    path("store/", include("apps.store.urls")),
    path("cart/", include("apps.carts.urls")),
    path("accounts/", include("apps.accounts.urls")),
    path("orders/", include("apps.orders.urls")),
    path("weather_clothes/", include("apps.weather_clothes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

flairstyle_shop/apps/carts/models.py
from apps.accounts.models import Account
from apps.store.models import Product
from apps.store.models import Variation
from django.db import models


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self) -> int:
        return self.product.price * self.quantity

    def __str__(self) -> str:
        return self.product.product_name

flairstyle_shop/apps/store/models.py
from apps.accounts.models import Account
from apps.category.models import Category
from django.db import models
from django.db.models import Avg
from django.db.models import Count
from django.db.models.query import QuerySet
from django.urls import reverse
from typing import Literal
from typing import Self


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to="photos/products")
    stock = models.IntegerField(null=False, default=0)
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    suitable_temperature_min = models.IntegerField(null=False, default=-100)
    suitable_temperature_max = models.IntegerField(null=False, default=100)

    def get_url(self: Self) -> str:
        return reverse("product_detail", args=[self.category.slug, self.slug])

    def average_review(self: Self) -> float | Literal[0]:
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg("rating"))
        avg = 0
        if reviews["average"] is not None:
            avg = float(reviews["average"])
        return avg

    def count_review(self: Self) -> int:
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count("id"))
        count = 0
        if reviews["count"] is not None:
            count = int(reviews["count"])
        return count

    def __str__(self: Self) -> str:
        return self.product_name


class VariationManager(models.Manager):
    def colours(self: Self) -> QuerySet:
        return super().filter(variation_category="color", is_active=True)

    def sizes(self: Self) -> QuerySet:
        return super().filter(variation_category="size", is_active=True)


variation_category_choice = (("color", "color"), ("size", "size"))


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self: Self) -> str:
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self: Self) -> str:
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)  # type: ignore
    image = models.ImageField(upload_to="store/products", max_length=255)

    def __str__(self: Self) -> str:
        return self.product.product_name

    class Meta:
        verbose_name = "product_gallery"
        verbose_name_plural = "Product Gallery"

flairstyle_shop/apps/store/forms.py
from apps.store.models import ReviewRating
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ["subject", "review", "rating"]

flairstyle_shop/apps/carts/views.py
from .models import Cart
from .models import CartItem
from apps.store.models import Product
from apps.store.models import Variation
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import HttpResponsePermanentRedirect
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from typing import Any


# TODO: Move to business logic
def _cart_id(request: HttpRequest) -> Any | None:
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


# TODO: Fix this
# ERROR: 'add_cart' is too complex (22)Flake8(C901)
def add_cart(request, product_id) -> HttpResponseRedirect | HttpResponsePermanentRedirect:  # noqa: C901
    current_user = request.user
    product = get_object_or_404(Product, id=product_id)
    if current_user.is_authenticated:
        product_variation = []
        if request.method == "POST":
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                # TODO: Fix this
                # ERROR: Bare except 'except:' usedFlake8(E722)
                except:  # noqa: E722
                    pass
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(
                product=product,
                user=current_user,
            )
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                # TODO: Fix this
                # ERROR: Cannot access member "id" for type "CartItem"
                id.append(item.id)  # type: ignore

            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                cart_item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    user=current_user,
                )
                if len(product_variation) > 0:
                    cart_item.variations.clear()
                    cart_item.variations.add(*product_variation)
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
        return redirect("cart")
    else:
        product_variation = []
        if request.method == "POST":
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                # TODO: Fix this
                # ERROR: Bare except 'except:' usedFlake8(E722)
                except:  # noqa: E722
                    pass
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(
                product=product,
                cart=cart,
            )
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                # TODO: Fix this
                # ERROR: Cannot access member "id" for type "CartItem"
                id.append(item.id)  # type: ignore

            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                cart_item = CartItem.objects.create(
                    product=product,
                    quantity=1,
                    cart=cart,
                )
                if len(product_variation) > 0:
                    cart_item.variations.clear()
                    cart_item.variations.add(*product_variation)
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
        return redirect("cart")


def remove_cart_item(request, product_id, cart_item_id) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect("cart")


def remove_cart(request, product_id, cart_item_id) -> HttpResponseRedirect | HttpResponsePermanentRedirect:
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = get_object_or_404(CartItem, product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = get_object_or_404(Cart, product=product, cart=cart, id=cart_item_id)
    # TODO: Fix this
    # ERROR: Cannot access member "quantity" for type "Cart"
    if cart_item.quantity > 1:  # type: ignore
        cart_item.quantity -= 1  # type: ignore
        cart_item.save()
    else:
        cart_item.delete()
    return redirect("cart")


def cart(request, total=0, grand_total=0, tax=0, quantity=0, cart_items=None) -> HttpResponse:
    try:
        if request.user.is_authenticated:
            cart_items = (
                CartItem.objects.select_related("product__category")
                .prefetch_related(
                    Prefetch(
                        "variations",
                        queryset=Variation.objects.all().only("variation_category", "variation_value"),
                    )
                )
                .filter(user=request.user, is_active=True)
                .only(
                    "product__product_name",
                    "product__price",
                    "quantity",
                    "product__category__slug",
                    "product__images",
                    "product__slug",
                    "is_active",
                )
            )
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = (
                CartItem.objects.select_related("product__category")
                .prefetch_related(
                    Prefetch(
                        "variations",
                        queryset=Variation.objects.all().only("variation_category", "variation_value"),
                    )
                )
                .filter(cart=cart, is_active=True)
                .only(
                    "product__product_name",
                    "product__price",
                    "quantity",
                    "product__category__slug",
                    "product__images",
                    "product__slug",
                    "is_active",
                )
            )
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))

    context = {
        "cart_items": cart_items,
        "total": total,
        "quantity": quantity,
        "tax": tax,
        "grand_total": grand_total,
    }
    return render(request, "store/cart.html", context)


@login_required(login_url="login")
def checkout(request, total=0, grand_total=0, tax=0, quantity=0, cart_items=None) -> HttpResponse:
    cart_items = (
        CartItem.objects.select_related("product__category")
        .prefetch_related(
            Prefetch(
                "variations",
                queryset=Variation.objects.all().only("variation_category", "variation_value"),
            )
        )
        .filter(user=request.user, is_active=True)
        .only(
            "product__product_name",
            "product__price",
            "quantity",
            "product__category__slug",
            "product__images",
            "product__slug",
            "is_active",
        )
    )
    for cart_item in cart_items:
        total += cart_item.product.price * cart_item.quantity
        quantity += cart_item.quantity
    tax = (2 * total) / 100
    grand_total = total + tax

    context = {
        "cart_items": cart_items,
        "total": total,
        "quantity": quantity,
        "tax": tax,

flairstyle_shop/templates/store/product_detail.html
{% extends "base.html" %}
{% block content %}

<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
              <center><img src="{{ single_product.images.url }}" /></center>
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <ul class="thumb">
            <li>
              <a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}"
                  alt="Product Image"></a>
              {% for i in product_gallery %}
              <a href="{{ i.image.url }}" target="mainImage"><img src="{{ i.image.url }}" alt="Product Image"></a>
              {% endfor %}
            </li>
          </ul>
          <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_cart' single_product.id %}" method='post'>
            {% csrf_token %}
            <article class="content-body">
              <h2 class="title">{{ single_product.product_name }}</h2>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if single_product.average_review < 0.5 %}-o{% elif  single_product.average_review >= 0.5 and  single_product.average_review < 1 %}-half-o{% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.average_review < 1.5 %}-o{% elif  single_product.average_review >= 1.5 and  single_product.average_review < 2 %}-half-o{% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.average_review < 2.5 %}-o{% elif  single_product.average_review >= 2.5 and  single_product.average_review < 3 %}-half-o{% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.average_review < 3.5 %}-o{% elif  single_product.average_review >= 3.5 and  single_product.average_review < 4 %}-half-o{% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.average_review < 4.5 %}-o{% elif  single_product.average_review >= 4.5 and  single_product.average_review < 5 %}-half-o{% endif %}"
                    aria-hidden="true"></i>
                  <span>{{ single_product.count_review }} Отзывы</span>
                </span>
              </div>
              <div class="mb-3">
                <var class="price h4">{{ single_product.price }} ₽</var>
              </div>
              <p>{{ single_product.description }}</p>
              <hr />
              <div class="row">
                <div class="item-option-select">
                  <h6>Выбрать цвет</h6>
                  <select name="color" class='form-control' required>
                    <option value="" disabled selected>Выбрать</option>
                    {% for i in single_product.variation_set.colours %}
                    <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <div class="row">
                <div class="item-option-select">
                  <h6>Выбрать размер</h6>
                  <select name="size" class='form-control' required>
                    <option value="" disabled selected>Выбрать</option>
                    {% for i in single_product.variation_set.sizes %}
                    <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- row.// -->
              <hr />
              {% if single_product.stock <= 0 %}
              <h5>Нет в наличии</h5>
              {% else %}
              <button type='submit' class="btn btn-primary"> <span class="text">В корзину
              </span> <i class="fas fa-shopping-cart"></i></button>
              {% endif %}
            </article>
            <!-- product-info-aside .// -->
          </form>
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    <br />
    <div class="row">
      <div class="col-md-9">

        <form action="{% url 'submit_review' single_product.id %}" method="post">

          {% csrf_token %}
          <h5>Написать отзыв</h5>
          <div>
            <label>Как оцените товар?</label>
            <br>
            <div class="rate">
              <input type="radio" name="rating" id="rating10" value="5" required>
              <label for="rating10" title="5"></label>
              <input type="radio" name="rating" id="rating9" value="4.5" required>
              <label for="rating9" title="4.5" class="half"></label>
              <input type="radio" name="rating" id="rating8" value="4" required>
              <label for="rating8" title="4"></label>
              <input type="radio" name="rating" id="rating7" value="3.5" required>
              <label for="rating7" title="3.5" class="half"></label>
              <input type="radio" name="rating" id="rating6" value="3" required>
              <label for="rating6" title="3"></label>
              <input type="radio" name="rating" id="rating5" value="2.5" required>
              <label for="rating5" title="2.5" class="half"></label>
              <input type="radio" name="rating" id="rating4" value="2" required>
              <label for="rating4" title="2"></label>
              <input type="radio" name="rating" id="rating3" value="1.5" required>
              <label for="rating3" title="1.5" class="half"></label>
              <input type="radio" name="rating" id="rating3" value="1" required>
              <label for="rating2" title="1"></label>
              <input type="radio" name="rating" id="rating1" value="0.5" required>
              <label for="rating1" title="0.5" class="half"></label>
            </div>
            <br>
            Заголовок отзыва:
            <input type="text" class="form-control" name="subject">
            <br>
            Отзыв:
            <textarea name="review" rows="4" class="form-control"></textarea>
            <br>
            {% if user.is_authenticated %}
            {% if order_product %}
            <input type="submit" value="Submit Review" class="btn btn-primary">
            {% else %}
            <p>Вы должны приобрести этот товар, чтобы оставить отзыв.
              {% endif %}
              {% else %}
              <p>Вы должны войти, чтобы оставить отзыв. <span><a href="{% url 'login' %}">Войти</a></span></p>
              {% endif %}

          </div>
          {% include "includes/alerts.html" %}
        </form>
        <br>
        <header class="section-heading">
          <h3>Отзывы покупателей</h3>
          <div class="rating-star">
            <span>
              <i class="fa fa-star{% if single_product.average_review < 0.5 %}-o{% elif  single_product.average_review >= 0.5 and  single_product.average_review < 1 %}-half-o{% endif %}"
                aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.average_review < 1.5 %}-o{% elif  single_product.average_review >= 1.5 and  single_product.average_review < 2 %}-half-o{% endif %}"
                aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.average_review < 2.5 %}-o{% elif  single_product.average_review >= 2.5 and  single_product.average_review < 3 %}-half-o{% endif %}"
                aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.average_review < 3.5 %}-o{% elif  single_product.average_review >= 3.5 and  single_product.average_review < 4 %}-half-o{% endif %}"
                aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.average_review < 4.5 %}-o{% elif  single_product.average_review >= 4.5 and  single_product.average_review < 5 %}-half-o{% endif %}"
                aria-hidden="true"></i>
              <span>{{ single_product.count_review }} Отзывы</span>
            </span>
          </div>
        </header>
        {% for review in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">
            <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle" />
            <div class="text">
              <span class="date text-muted float-md-right">{{ review.updated_at }}</span>
              <h6 class="mb-1">{{ review.user.full_name }}</h6>
              <div class="rating-star">
                <span>
                  <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %}"
                    aria-hidden="true"></i>
                  <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %}"
                    aria-hidden="true"></i>
                </span>
              </div>
            </div>
          </div>
          <!-- icontext.// -->
          <div class="mt-3">
            <h6>{{ review.subject }}</h6>
            <p>
              {{ review.review }}
            </p>
          </div>
        </article>
        {% endfor %}

      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}